---
- hosts: redhat-servers
  become:
    true
  become_method:
    su
  become_user:
    ubuntu
  remote_user:
    ubuntu
  roles:
   - epel
   - nginx

- hosts: debian-servers
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ansible
  roles:
   -