FROM jenkins/jenkins:2.346.1-jdk11
USER root
RUN apt-get install -y lsb-release
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
  https://download.docker.com/linux/debian/gpg
RUN echo "deb [arch=$(dpkg --print-architecture) \
  signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
  https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
RUN apt-get install -y git
RUN mkdir /var/jenkins_home/git \      
           cd /var/jenkins_home/git \        
           git clone https://github.com/dontesii/devops_SB.git          
COPY       Task63  /var/jenkins_home/jobs/
RUN  apt-get install -y docker-ce-cli
USER jenkins
RUN jenkins-plugin-cli --plugins "blueocean:1.25.5 docker-workflow:1.28"
